POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Example Name",
    "id": 5,
    "number": 12345
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Juan Perez",
    "number": 345678
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Sandra Flores"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": 987654
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
    "name": "Arto Hellas", 
    "number": "040-123456"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
    "name": "abc", 
    "number": "040-123456"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
    "name": "Juanito", 
    "number": "2-3456"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
    "name": "Juanito", 
    "number": "3456-234"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
    "name": "Juanito", 
    "number": "34-67h77665"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
    "name": "Yolanda Ferrero", 
    "number": "040-22334455"
}